quarkus:
  hibernate-orm:
    schema-management:
      strategy: drop-and-create

"%dev":
  quarkus:
    datasource:
      devservices:
        # Keep local dev predictable, but avoid collisions in tests.
        port: 5432
